[project]
name = "evaluate"
channels = [
    "conda-forge",
    "https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/",
    "https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/",
    "https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/",
    "https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/"
]
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]          # 默认feature，目前空着也行

[feature.protein]
dependencies = { busco = ">=6.0.0,<7", omark = ">=0.3.1,<0.4" }

[feature.transcript]
dependencies = { numpy = "1.23.5.*", pandas = "1.5.3.*", sqlalchemy = "1.4.54.*", mikado = ">=2.3.4,<3", hisat2 = ">=2.2.1,<3", stringtie = "3.0.0.*", gffread = ">=0.12.7,<0.13", portcullis = ">=1.2.4,<2", perl-uri = ">=5.34,<6", gnuplot = ">=5.4.10,<6" }

[environments]
protein    = ["protein"]
transcript = ["transcript"]
